### ISSUE TITLE
reference coded as in-text mention?

### ISSUE THREAD

**Issue by jameshowison** [howisonlab/softcite-dataset#191]
Hi Minjeong aka @mjsong1201, cc @jlcohoon 

Thanks for all the work you've been doing on softcite.  I was doing some analysis and came across this selection: PMC4683424_MS03  

It's marked as an in-text selection, but seems to be a reference?  Could you check it out and let me know what's happening?

Perhaps you were coding the reference lists as well as the main text?  Hannah, do we have an explicit note that we don't need to code references that aren't associated with an intext mention?

Thanks,
James

**Comment by mjsong1201** [comment]
Hi James,

I think I double-checked the name of the software with a search bar at the
end, and found one in the reference list which wasn't mentioned above in
the text, so I coded it as an in-text mention. I'm sorry if I shouldn't
have done this. Should I delete that one?

Oh, I have another question, the current paper(PMC1636350) I'm working on
has a lot of mentions of 'programs.' The paper puts them as 'programs' and
not softwares, and when I google them, some of them look like databases and
some look like softwares. The paper is about their program called MUMMALS,
and it seems like the word appears in every sentence in some of the
sections (e.g. Discussion). I couldn't find enough information of this
program on google. Could you check if it's a software I need to code?

Best,
Minjeong

2017-10-19 16:54 GMT-05:00 James Howison <notifications@github.com>:

**Comment by jameshowison** [comment]
No worries, yes, delete PMC4683424_MS03 (no need to renumber other stuff).

From your description of the MUMMALS one we probably need to code each one.  Sorry!  Feel free to hold off on this one and run it by me in person?
