### ISSUE TITLE
trouble with article URLs?

### ISSUE THREAD

**Issue by jameshowison** [howisonlab/softcite-dataset#197]
@jlcohoon could you take a look at @sehreenali files?  The article URLs seem to have initials attached to them.  The article URL should just be the PMC code.  Could we fix those and commit them back?

Thanks,
James

**Comment by jameshowison** [comment]
Hi @sehreenali  and @jlcohoon any progress on this?

**Comment by sehreenali** [comment]
I went ahead and emailed Hannah about it and I’ll try to get it fixed as
soon as possible! Thanks for letting me know!

Sehreen Ali
