### ISSUE TITLE
.ttl to .csv conversion issues

### ISSUE THREAD

**Issue by kermitt2** [howisonlab/softcite-dataset#510]
I am using the .csv files right now (I didn't manage to parse directly the .ttl files with the Java [nxparser](https://github.com/nxparser/nxparser) for turtle) and I noticed missing "full quotes" in the `softcite_in_text_mention.csv file`, missing mentions in `softcite_code_applied.csv` and missing reference in `softcite_reference.csv` as compared to the turtle files. 

example: PMC5226643
******************************

* missing quotes

In PMC5226643, we find 8 mentions of the software `pMELTS`.

There is however only one "quote" in `softcite_in_text_mention.csv` entry:

```
PMC5226643_JWC01,jackchristen,PMC5226643,A pMELTS simulation (31) with the alphaMELTSinterface (32)of176Lu/177Hf during KREEP c,3,software,7,looked it up
```

In the .ttl files, we find correctly the 8 mentions+quotes (2 are in bibliographical references). 

* missing software names

Still for `pMELTS`, there are 4 softcite_code_applied.csv entries: 

```
PMC5226643_JWC01,jackchristen,software_was_used,true,
PMC5226643_JWC01,jackchristen,software_name,true,pMELTS
PMC5226643_JWC01,jackchristen,version_number,false,
PMC5226643_JWC01,jackchristen,version_date,false,
PMC5226643_JWC01,jackchristen,url,false,
PMC5226643_JWC01,jackchristen,creator,false,

PMC5226643_JWC05,jackchristen,software_was_used,true,
PMC5226643_JWC05,jackchristen,software_name,true,pMELTS
PMC5226643_JWC05,jackchristen,version_number,false,
PMC5226643_JWC05,jackchristen,version_date,false,
PMC5226643_JWC05,jackchristen,url,false,
PMC5226643_JWC05,jackchristen,creator,false,

PMC5226643_JWC07,jackchristen,software_was_used,true,
PMC5226643_JWC07,jackchristen,software_name,true,pMELTS
PMC5226643_JWC07,jackchristen,version_number,false,
PMC5226643_JWC07,jackchristen,version_date,false,
PMC5226643_JWC07,jackchristen,url,false,
PMC5226643_JWC07,jackchristen,creator,false,

PMC5226643_JWC08,jackchristen,software_was_used,true,
PMC5226643_JWC08,jackchristen,software_name,true,pMELTS
PMC5226643_JWC08,jackchristen,version_number,false,
PMC5226643_JWC08,jackchristen,version_date,false,
PMC5226643_JWC08,jackchristen,url,false,
PMC5226643_JWC08,jackchristen,creator,false,
```

Two other mentions in the .ttl files are missing in this .csv file (6 mentions are in the body, 2 in the bibliographical reference section). 

(note that for the other entries PMC5226643_JWC02, PMC5226643_JWC03, etc. corresponding to other software_name, there is also no quote in the .csv file, while they are present in the .ttl files). 

* missing reference

We have only one entry for this article in `softcite_reference.csv` which correspond to the callout (31) of the reported "in text mention". 

```
PMC5226643_Ghiorso01,PMC5226643_JWC01,PMC5226643,"M. S. Ghiorso, M. M. Hirschmann, P. W. Reiners, V. C. Kress III, The pMELTS: A revision ofMELTS for improved calculation of phase relations and major element partitioning related topartial melting of the mantle to 3 GPa.Geochem. Geophys. Geosyst.3,1–35 (2002)",jackchristen,7,publication
```

The reference corresponding to the callout (32) (same mention context/quote) is present in the .ttl file, but not in the .csv:

```
32. P. M. Smith, P. D. Asimow, Adiabat_1ph: A new public front-end to the MELTS, pMELTS,
    and pHMELTS models. Geochem. Geophys. Geosyst. 6, Q02004 (2005).
```

**Comment by kermitt2** [comment]
After looking a bit at the .ttl and the `export_dataset.tRmd`, it appears that:

* there are no missing software names in `softcite_code_applied.csv`, I made an error in my example, there are indeed 6 mentions+quotes (including 2 in bibliographical references) in the .ttl files (the mentions in the PDF and not in the .ttl files are one in a figure caption and one as section title, which another issue, but not related to csv conversion)

* the missing quotes in `softcite_in_text_mention.csv` are due to the fact that the .ttl are incomplete - this is not an issue of the SPARQL query in `export_dataset.Rmd`. For the given example, there is only one clause like this: 

```
pmcid:PMC5226643 a bioj:article ;
    ca:isTargetOf [ a ca:CodeApplication ;
            ca:appliesCode [ a citec:coded_no_in_text_mentions ;
                    citec:isPresent false ] ;
            ca:hasCoder "jackchristen" ] ;
    citec:has_in_text_mention pmcid:PMC5226643_JWC01 .
```

So only the quote for selection `pmcid:PMC5226643_JWC01` appears as a result of the query (given the criteria `?article citec:has_in_text_mention ?selection .`):

```
SELECT DISTINCT ?selection ?coder ?article ?quote ?page ?mention_type ?certainty ?memo
WHERE {
	?article citec:has_in_text_mention ?selection .
	?selection citec:full_quote ?quote ;
	           citec:on_pdf_page ?page ;
	           ca:isTargetOf [ ca:hasCoder ?coder ;
                             ca:appliesCode [ rdf:type citec:mention_type ;
                                              rdfs:label ?mention_type ;
                                              ca:certainty ?certainty ;
                                              ca:memo ?memo ]
                            ]
}
```

It is easy to fix by removing the constraint on the article:

```
```{r}

in_text_mention_q <- "SELECT DISTINCT ?selection ?coder ?quote ?page ?mention_type ?certainty ?memo
WHERE {
	?selection citec:full_quote ?quote ;
	           citec:on_pdf_page ?page ;
	           ca:isTargetOf [ ca:hasCoder ?coder ;
                             ca:appliesCode [ rdf:type citec:mention_type ;
                                              rdfs:label ?mention_type ;
                                              ca:certainty ?certainty ;
                                              ca:memo ?memo ]
                            ]
}
"

in_text_mentions <- SPARQL(url = softcite_ds, query = paste0(prefixes, in_text_mention_q), 
       format = "csv", extra=list(format="csv"))$results %>% 
  as.tibble %>% 
  mutate_at(vars(selection),
            funs(str_extract(.,"[#/]([^#/]+)$"))) %>%
  mutate_at(vars(selection), funs(str_sub(.,2))) %>% 
  write_csv(here::here("data/csv_dataset/softcite_in_text_mentions.csv"))
```

produce all the mentions correctly, but we are loosing the field `article`. Actually I think there is no way to get for an article all its selections, because of the incomplete .ttl. We can still get the article identifier as the prefix name of the `selection` (PMC5226643_JWC01), but it's a bit ad-hoc.

**Comment by jameshowison** [comment]
Thanks!  I've added a check that the headers are always to be there to our tests.  Now working through to fix all missing ones, then will produce the csv again.
