### ISSUE TITLE
Could we add another markup code indicating article subjects in the corpus file?

### ISSUE THREAD

**Issue by caifand** [howisonlab/softcite-dataset#643]
@jameshowison and I just came to the idea that it would be nice to have an additional markup code, applied to each excerpt from a PDF, which claims the subject of the article (e.g., pmc/econ/astronomy). Something like `<note>`/`<category>` or other? How applicable is it? @kermitt2

**Comment by kermitt2** [comment]
One possibility with the available DOI, is to access additional metadata like the subject headers of the CrossRef records. For instance: 
https://api.crossref.org/v1/works/10.1038/s41467-018-03730-x

-> "General Biochemistry, Genetics and Molecular Biology", "General Physics and Astronomy", "General Chemistry"

It corresponds to the WOS categories at journal level. So I think it's not available in general for conference papers, and it's not categories at article level - but it is I think not a problem for your idea.

**Comment by jameshowison** [comment]
This is simpler.  We made some broad categories using a) PMC open access
(mark as "biomedicine" or just "pmc") and then the Unpaywall categories
(aggregated up into "econ" and "astro" (although no astro actually got done
yet).

This is just the `article_set` field in
https://github.com/howisonlab/softcite-dataset/blob/master/data/csv_dataset/softcite_articles.csv

Would be great to show people how to get better sub-categories if they want
(via the DOIs) but for the moment we just want to mark these categories.
