### ISSUE TITLE
Data addition

### ISSUE THREAD

**Issue by kermitt2** [howisonlab/softcite-dataset#665]
Proposal for the addition of data to the repo:
- under `softcite-dataset/tei/`, all the TEI files corresponding to the PDF of the dataset, as converted by Grobid
- under `softcite-dataset/json/`, all the JSON file with the entity span information for the annotations
- under `softcite-dataset/final/`, the annotated corpus in TEI format

And I could put the python scripts that creates the JSON files from the Grobid TEI XML and the annotated corpus under 
`softcite-dataset/code/corpus/` ?

**Comment by jameshowison** [comment]
Yup. Looks good.  Hmmm, maybe we should call the annotated corpus files
`softcite-data/corpus` rather than `final`.

James Howison

Associate Professor
School of Information
University of Texas at Austin
http://james.howison.name

**Comment by kermitt2** [comment]
Ok! actually I forgot the `data/` level maybe, so:

- `softcite-dataset/data/tei/`
- `softcite-dataset/data/json/`
- `softcite-dataset/data/corpus/`

and `softcite-dataset/code/corpus/` for the related python stuff.

**Comment by jameshowison** [comment]
Great!

**Comment by jameshowison** [comment]
Working on these files.  Any idea what the empty files (well empty dict in the file) imply?

```sh
SOI-A14570-Howison:json howison$ grep -r \{} .
./PMC3049466.json:{}
./PMC3727320.json:{}
./10.1007%2Fs11166-011-9127-z.json:{}
./PMC4506345.json:{}
./PMC2808573.json:{}
./PMC4266938.json:{}
./PMC5238813.json:{}
./PMC5041470.json:{}
./PMC3284254.json:{}
./PMC3065992.json:{}
./PMC4683424.json:{}
```

**Comment by kermitt2** [comment]
The JSON files are still work-in-progress, not entirely finished... thanks for pointing to these files, it's a bug in the conversion process I think because the TEI files look good.  

(this issue was about the location for the files in the repo, it's why I closed it :) I will update on the json files in #666)

**Comment by jameshowison** [comment]
Great.  I'll follow #666.
