### ISSUE TITLE
Questions on TEI data and tags therein

### ISSUE THREAD

**Issue by jd-coderepos** [howisonlab/softcite-dataset#675]
First of all, such a wonderful data source! Kudos to the creators.

Referring to the TEI data, e.g. https://github.com/howisonlab/softcite-dataset/blob/master/data/corpus/softcite_corpus_econ-compact.tei.xml and also to the data model https://data.gesis.org/somesci/index.html#model. How does one obtain the allusion information for any particular software - which xml tags should we be looking for?

Also it appears that some software mentions have `xml:id` including a suffix with pattern `*-simple-[number].` Does the `simple` actually denote something, maybe about the allusion perhaps?

Thanks for your time. :)

**Comment by jameshowison** [comment]
Thanks! By ‘allusion’ do you mean what we call a mention? Some software mentioned in the text?

**Comment by jd-coderepos** [comment]
Sorry looks like I confused resources a bit here.... but softcite and SoMeSci seem to share a lot in common :)
